# Generated by Django 3.2.5 on 2021-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productSpecification', models.CharField(max_length=1000)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productLocation', models.CharField(max_length=100)),
                ('productTime', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
