# Generated by Django 3.2.5 on 2021-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20210727_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.ImageField(default='img/icon.png', upload_to='Images'),
        ),
    ]
