# Generated by Django 3.2.5 on 2021-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
