# Generated by Django 3.2.5 on 2021-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('bid_price', models.IntegerField(default=0)),
            ],
        ),
    ]
