# Generated by Django 3.2.5 on 2021-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0008_rename_winners_bidwinner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bidWinner',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
